[platformio]
;default_envs = debug  ; Set environment to debug
default_envs = release  ; Set environment to release

; Common settings for all environments
[env]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200

; Debug environment
[env:debug]
lib_deps = jdolinay/avr-debugger@^1.5
debug_tool = avr-stub
debug_port = COM7 ;; If COM port is > COM9 then -> \\.\COM10
build_flags = 
    -D DEBUG_MODE
    -O0  ; Disable optimizations for better debugging
debug_init_break = tbreak main

; Release environment
[env:release]
build_flags = 
    -D RELEASE_MODE
    -Os  ; Optimize for size
